@hostname = http://127.0.0.1:5002/api/v1/account-number-management

# all
###
GET {{hostname}}?orderByCol=id&orderByAsc=true&show_active_data=true&paginate=10   HTTP/1.1

# get
###
GET {{hostname}}/1 HTTP/1.1

# store
###
POST  {{hostname}}/store HTTP/1.1
content-type: application/json

{
    "account_id": 1,
    "number":1
}

# update
###
POST {{hostname}}/update HTTP/1.1 
content-type: application/json

{
    "id":1,
    "account_id": 2,
    "number":1
}



# forget mail
###
POST {{hostname}}/forget HTTP/1.1
content-type: application/json

{}

# soft delete
###
POST  {{hostname}}/soft-delete HTTP/1.1
content-type: application/json

{
    "id": 1
}

# restore
###
POST  {{hostname}}/restore HTTP/1.1
content-type: application/json

{
    "id": 1
}

# block
###
POST  {{hostname}}/block HTTP/1.1
content-type: application/json

{
    "id": 6
}


# destroy
###
POST  {{hostname}}/destroy HTTP/1.1
content-type: application/json

{
    "id": 1
}