@hostname = http://127.0.0.1:5002/api/v1/project-payment-management

# all
###
GET {{hostname}}?orderByCol=id&orderByAsc=true&show_active_data=true&paginate=10   HTTP/1.1

# get
###
GET {{hostname}}/1 HTTP/1.1

# store
###
POST  {{hostname}}/store HTTP/1.1
content-type: application/json

{
    "account_log_id": 1,
    "user_id":1,
    "date": "2024-01-01",
    "project_id":5,
    "reference_user_id": true,
    "amount": true,
    "reference_user_id":1,
    "type": "booking_money"
}

# update
###
POST {{hostname}}/update HTTP/1.1 
content-type: application/json

{
    "id":1,
    "account_log_id": 1,
    "user_id":1,
    "date": "2024-01-01",
    "project_id":5,
    "reference_user_id": true,
    "amount": true,
    "reference_user_id":1,
    "type": "installments"
}



# forget mail
###
POST {{hostname}}/forget HTTP/1.1
content-type: application/json

{}

# soft delete
###
POST  {{hostname}}/soft-delete HTTP/1.1
content-type: application/json

{
    "id": 1
}

# restore
###
POST  {{hostname}}/restore HTTP/1.1
content-type: application/json

{
    "id": 1
}

# block
###
POST  {{hostname}}/block HTTP/1.1
content-type: application/json

{
    "id": 6
}


# destroy
###
POST  {{hostname}}/destroy HTTP/1.1
content-type: application/json

{
    "id": 1
}