@hostname = http://127.0.0.1:5002/api/v1/project-management

# all
###
GET {{hostname}}?orderByCol=id&orderByAsc=true&show_active_data=true&paginate=10   HTTP/1.1

# get
###
GET {{hostname}}/1 HTTP/1.1

# store
###
POST  {{hostname}}/store HTTP/1.1
content-type: application/json

{
    "uid": "project one",
    "title": "title",
    "location": "location 1",
    "description": "description",
    "per_share_cost": 100,
    "map": "slslsl",
    "video": "video",
    "image":"image",
    "aveneue":"aveneue",
    "plot":"plot",
    "road":"road"
}


# update
###
POST {{hostname}}/update HTTP/1.1 
content-type: application/json

{
    "id": 1,
    "uid": "project one",
    "title": "title update",
    "location": "location 1",
    "description": "description",
    "per_share_cost": 100,
    "map": "slslsl",
    "video": "video",
    "image":"image",
    "aveneue":"aveneue",
    "plot":"plot",
    "road":"road"
}

# login
###
POST {{hostname}}/login HTTP/1.1 
content-type: application/json
# Authorization: {{token}}

{
    "email": "admin1@gmail.com",
    "password": "12345678"
}

# logout
###
POST {{hostname}}/logout HTTP/1.1
content-type: application/json

{}

# forget mail
###
POST {{hostname}}/forget HTTP/1.1
content-type: application/json

{}

# soft delete
###
POST  {{hostname}}/soft-delete HTTP/1.1
content-type: application/json

{
    "id": 1
}

# restore
###
POST  {{hostname}}/restore HTTP/1.1
content-type: application/json

{
    "id": 1
}


# destroy
###
POST  {{hostname}}/destroy HTTP/1.1
content-type: application/json

{
    "id": 1
}